name: like-banner

on:
  schedule:
    - cron:  '* * * * *' 

jobs:
  get-likes:
    runs-on: macOS-latest
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: twitter-like-badge
      - name: git config
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
      - name: TWITTER API with curl
        run: |
          curl 'https://api.twitter.com/2/tweets?ids=1511034067344572422&tweet.fields=public_metrics&expansions=attachments.media_keys&media.fields=public_metrics' --header 'Authorization: Bearer ${{ secrets.TWITTER_BEARER_TOKEN }}' -o likes
        shell: bash
      - name: Commit and Push changes
        run: |
          git add --all
          git commit -am 'Automatic commit to update latest twitter likes data'
      - name: Push changes
        run: |
          git push

